# Introduction to Python

## Textual Data

In [5]:
#To print result in Python
message = 'Hello World'
print(message)

Hello World


In [6]:
#To know the length of the string
print(len(message))

11


In [3]:
#Indexing starts with 0
print(message[0])

H


In [10]:
#Indexing to print entire word (where 0 is inclusive while 5 is exclusive)
print(message[0:5])
print(message[:5])
print(message[6:])

Hello
Hello
World


In [11]:
#To print message in lowercase
print(message.lower())

hello world


In [13]:
#To print message in uppercase
print(message.upper())

HELLO WORLD


In [14]:
#To count certain number of letters
print(message.count('l'))

3


In [15]:
#To find (results index of the word/letter)
print(message.find('World'))

6


In [19]:
#To replace anything

message = message.replace('World','Universe') #(Word/letter to be replaced, New word)
print(message)

Hello Universe


In [23]:
#
greeting = 'Hello'
name = 'Harshit'
message = greeting + '! ' + name
print(message)

Hello! Harshit


In [28]:
#String Formatting
greeting = 'Hello'
name = 'Harshit'
message = '{}! {}. Welcome'.format(greeting, name)
print(message)

Hello! Harshit. Welcome


In [32]:
#Sting Formatting with f-strings (in Python-3 only)
greeting = 'Hello'
name = 'Harshit'
message = f'{greeting.lower()}! {name.upper()}. Welcome'
print(message)

hello! HARSHIT. Welcome


In [33]:
#  To find attributes and functions available wrt to a variable
greeting = 'Hello'
name = 'Harshit'

print(dir(name))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [36]:
#To find the help on available strings attributes and functions

print(help(str.strip))

Help on method_descriptor:

strip(self, chars=None, /)
    Return a copy of the string with leading and trailing whitespace removed.
    
    If chars is given and not None, remove characters in chars instead.

None


## Numeric Data

In [39]:
#To find the class
num = 3
print(type(num))

<class 'int'>


In [38]:
num = 3.14
print(type(num))

<class 'float'>


In [41]:
#Arithmetic Operators:
#Addition:3+2
#Subtraction: 3-2
#Multiplication: 3*2
#Division: 3/2
#Floor Division: 3//2
#Exponent: 3**2
#Modulus: 3%2 (Useful to check odd or even)

print(3+2)
print(3-2)
print(3*2)
print(3/2)
print(3//2)
print(3**2)
print(3%2)

5
1
6
1.5
1
9
1


In [42]:
#To make changes in variable with numerical data
num = 1 
num += 1
print(num)

2


In [44]:
#To make absolute value
print(abs(-3))

3


In [47]:
#To round off
print(round(3.75,1))

3.8


In [51]:
#Comparison Operators
#Equal: 3 == 2
#Not Equal: 3 != 2
#Greater Than: 3 > 2
#Less Than: 3 < 2
#Greater than or equal: 3 >= 2
#Less or equal: 3 <= 2

num_1 = 2
num_2 = 3

print(num_1 == num_2)
print(num_1 != num_2)
print(num_1 > num_2)
print(num_1 < num_2)
print(num_1 >= num_2)
print(num_1 <= num_2)

False
True
False
True
False
True


In [53]:
#Cast from str to int
num_1 = '100'
num_2 = '200'

num_1 = int(num_1)
num_2 = int(num_2)
print(num_1 + num_2)

300


## Lists, Tuples and Sets

In [54]:
#Lists allows to work on lists of values

courses = ['History','Maths','Physics','Comp Sci']
print(courses)

['History', 'Maths', 'Physics', 'Comp Sci']


In [55]:
print(len(courses))

4


In [60]:
#To index the lists
print(courses[3])
print(courses[-1])

Comp Sci
Comp Sci


In [65]:
print(courses[:3])

['History', 'Maths', 'Physics']


In [69]:
#To add another item in lists using APPEND
courses = ['History','Maths','Physics','Comp Sci']
courses.append('Art')
print(courses)

['History', 'Maths', 'Physics', 'Comp Sci', 'Art']


In [70]:
#To add item at specific location in lists using INSERT
courses = ['History','Maths','Physics','Comp Sci']
courses.insert(3, 'Art')
print(courses)

['History', 'Maths', 'Physics', 'Art', 'Comp Sci']


In [71]:
#To add multiple items in lists using EXTEND
courses = ['History','Maths','Physics','Comp Sci']
courses_2 = ['Art','Education']
courses.extend(courses_2)
print(courses)

['History', 'Maths', 'Physics', 'Comp Sci', 'Art', 'Education']


In [73]:
#To remove items from lists using REMOVE
courses = ['History','Maths','Physics','Comp Sci']
courses.remove('Maths')
print(courses)

['History', 'Physics', 'Comp Sci']


In [74]:
#To remove items using POP (removes last item in list)
courses = ['History','Maths','Physics','Comp Sci']
courses.pop()
print(courses)

['History', 'Maths', 'Physics']


In [76]:
#To reverse the order of list
courses = ['History','Maths','Physics','Comp Sci']
courses.reverse()
print(courses)

['Comp Sci', 'Physics', 'Maths', 'History']


In [83]:
#To sort the list
courses = ['History','Maths','Physics','Comp Sci']
courses.sort()
print(courses)

['Comp Sci', 'History', 'Maths', 'Physics']


In [85]:
#To sort the numbers
courses = ['History','Maths','Physics','Comp Sci']
nums = [1,5,2,3,4]
courses.sort()
nums.sort()
print(courses)
print(num)

['Comp Sci', 'History', 'Maths', 'Physics']
2


In [88]:
#To sort in descending order
courses = ['History','Maths','Physics','Comp Sci']
nums = [1, 5, 2, 3, 4]
courses.sort(reverse=True)
nums.sort(reverse=True)
print(courses)
print(num)

['Physics', 'Maths', 'History', 'Comp Sci']
2


In [90]:
#To get min, max, sum values
nums = [1, 5, 2, 4, 3]
print(min(nums))
print(max(nums))
print(sum(nums))

1
5
15


In [93]:
#To find the index of vertain value in lists
courses = ['History','Maths','Physics','Comp Sci']
print(courses.index('Comp Sci'))

3


In [94]:
#To find the index of vertain value in lists
courses = ['History','Maths','Physics','Comp Sci']
print('Comp Sci' in courses)

True


In [95]:
#To loop through values in list
courses = ['History','Maths','Physics','Comp Sci']
for item in courses:
    print(item)

History
Maths
Physics
Comp Sci


In [97]:
#To loop through values and index in list
courses = ['History','Maths','Physics','Comp Sci']

for index, course in enumerate(courses,start = 1):
    print(index, course)

1 History
2 Maths
3 Physics
4 Comp Sci


In [98]:
#To convert str to csv
courses = ['History','Maths','Physics','Comp Sci']
course_str = ', '.join(courses)
print(course_str)

History, Maths, Physics, Comp Sci


In [99]:
#To converr csv to str
courses = ['History','Maths','Physics','Comp Sci']
course_str = ', '.join(courses)
new_list = course_str.split(', ')
print(course_str)
print(new_list)

History, Maths, Physics, Comp Sci
['History', 'Maths', 'Physics', 'Comp Sci']


In [100]:
#Mutable
list_1 = ['History','Maths','Physics','Comp Sci']
list_2 = list_1
print(list_1)
print(list_2)

list_1[0] = 'Art'
print(list_1)
print(list_2)

['History', 'Maths', 'Physics', 'Comp Sci']
['History', 'Maths', 'Physics', 'Comp Sci']
['Art', 'Maths', 'Physics', 'Comp Sci']
['Art', 'Maths', 'Physics', 'Comp Sci']


In [101]:
#Immutable

tuple_1 = ('History','Maths','Physics','Comp Sci')
tuple_2 = tuple_1

print(tuple_1)
print(tuple_2)

('History', 'Maths', 'Physics', 'Comp Sci')
('History', 'Maths', 'Physics', 'Comp Sci')


In [118]:
#Sets: Values that are unordered and no duplicate
cs_courses = {'History','Maths','Physics','Comp Sci'}
print(cs_courses)

{'Maths', 'Comp Sci', 'History', 'Physics'}


In [119]:
#Membership test
cs_courses = {'History','Maths','Physics','Comp Sci'}
print('Maths' in cs_courses)

True


In [122]:
#Sets Operations
cs_courses = {'History','Maths','Physics','Comp Sci'}
art_courses = {'History','Maths','Art','Design'}
print(cs_courses.intersection(art_courses))
print(cs_courses.union(art_courses))
print(cs_courses.difference(art_courses))

{'Maths', 'History'}
{'Art', 'Comp Sci', 'History', 'Design', 'Maths', 'Physics'}
{'Comp Sci', 'Physics'}


In [ ]:
#Empty lists
empty_list = [] #or
empty_list = list()

#Empty Tuples
empty_tuple = () #or
empty_tuple = tuple()

#Empty Sets
empty_set = {} #This is wrong, It's a dictionary
empty_set = set()

## Dictionary
Key-Value pairing

In [125]:
#To define key and value in dictionary named "student"
student = {'name': 'John', 'age': 25, 'courses': ['Math','CompSci']}
print(student)
print(student['name'])
print(student['courses'])

{'name': 'John', 'age': 25, 'courses': ['Math', 'CompSci']}
John
['Math', 'CompSci']


In [127]:
#When error value returned in Dict, use GET function
student = {'name': 'John', 'age': 25, 'courses': ['Math','CompSci']}
print(student.get('phone','Not Found'))

Not Found


In [130]:
#To update the dict
student = {'name': 'John', 'age': 25, 'courses': ['Math','CompSci']}
student.update({'name': 'Jane','age': 26,'phone': 5555555555})
print(student)

{'name': 'Jane', 'age': 26, 'courses': ['Math', 'CompSci'], 'phone': 5555555555}


In [136]:
#To delete item in Dict
student = {'name': 'John', 'age': 25, 'courses': ['Math','CompSci']}
del student['age']
print(student)

{'name': 'John', 'courses': ['Math', 'CompSci']}


In [138]:
#OR
student = {'name': 'John', 'age': 25, 'courses': ['Math','CompSci']}
age = student.pop('age')
print(age)

25


In [139]:
#To loop key and values in Dict
student = {'name': 'John', 'age': 25, 'courses': ['Math','CompSci']}
print(len(student))

3


In [140]:
#To loop key and values in Dict
student = {'name': 'John', 'age': 25, 'courses': ['Math','CompSci']}
print(student.keys())

dict_keys(['name', 'age', 'courses'])


In [141]:
#To loop key and values in Dict
student = {'name': 'John', 'age': 25, 'courses': ['Math','CompSci']}
print(student.items())

dict_items([('name', 'John'), ('age', 25), ('courses', ['Math', 'CompSci'])])


In [142]:
#To loop key and values in Dict
student = {'name': 'John', 'age': 25, 'courses': ['Math','CompSci']}
for key, value in student.items() :
    print(key, value)

name John
age 25
courses ['Math', 'CompSci']


## Conditionals & Booleans

In [143]:
#Conditional Samples
if True:
    print('Conditional was True')

Conditional was True


In [144]:
#Conditional Samples
language = 'Python'
if language == 'Python':
    print('Conditional was True')

Conditional was True


In [146]:
#Comparison Operators
#Equal: 3 == 2
#Not Equal: 3 != 2
#Greater Than: 3 > 2
#Less Than: 3 < 2
#Greater than or equal: 3 >= 2
#Less or equal: 3 <= 2
#Object Identity: is
language = 'Python'
if language == 'Java':
    print('Language is python')
else:
    print('No match')

No match


In [151]:
#To check 3 or more conditions at a time
language = 'Java'
if language == 'Python':
    print('Language is python')
elif language == 'Java':
    print('Language is Java')
elif language == 'JavaScript':
    print('Language is JavaScript')
else:
    print('No match')

Language is Java


In [155]:
#Boolean Operations
#AND (Both conditions are met)
#OR (One of the condition is met)
#NOT

user = 'Admin'
logged_in = False

if user == 'Admin' or logged_in:
    print('Admin Page')
else: 
    print('Bad Credentials')

Admin Page


In [161]:
#Object Identity

a = [1,2,3]
b = a
print(id(a))
print(id(b))
print (a is b)

2794935073152
2794935073152
True


In [162]:
#False Values:
#False
#None
#Zero of any numeric type
#Any empty sequence, ex: '',(),[]
#Any empty mapping, ex: {}
condition = False

if condition:
    print('Evaluated to True')
else:
    print('Evaluated to False')

Evaluated to False


In [163]:
condition = None

if condition:
    print('Evaluated to True')
else:
    print('Evaluated to False')

Evaluated to False


In [164]:
condition = 0

if condition:
    print('Evaluated to True')
else:
    print('Evaluated to False')

Evaluated to False


In [167]:
condition = []

if condition:
    print('Evaluated to True')
else:
    print('Evaluated to False')

Evaluated to False


In [168]:
condition = {}

if condition:
    print('Evaluated to True')
else:
    print('Evaluated to False')

Evaluated to False


In [169]:
condition = []

if condition:
    print('Evaluated to True')
else:
    print('Evaluated to False')

Evaluated to False


## Loops and Iterations

In [170]:
#Loop example
nums = [1,2,3,4,5]
for num in nums:
    print(num)

1
2
3
4
5


In [178]:
#Break
nums = [1,2,3,4,5]
for num in nums:
    if num == 3:
        print('Found!')
        break
    print(num)

1
2
Found!


In [179]:
#Continue
nums = [1,2,3,4,5]
for num in nums:
    if num == 3:
        print('Found!')
        continue
    print(num)

1
2
Found!
4
5


In [180]:
#Loop in Loop
nums = [1,2,3,4,5]
for num in nums:
    for letter in 'abc':
        print(num, letter)

1 a
1 b
1 c
2 a
2 b
2 c
3 a
3 b
3 c
4 a
4 b
4 c
5 a
5 b
5 c


In [185]:
#Alternate to Loop in Loop using RANGE function
for i in range(1,11):
    print (i)

1
2
3
4
5
6
7
8
9
10


In [201]:
#While loops
x = 0

while True:
    if x == 5:
        print('Found!')
        break
    print(x)
    x += 1

0
1
2
3
4
Found!


## Functions

In [205]:
#To create fucntion, use def
def hello_func():
    print('Hello Function!')
hello_func()

Hello Function!


In [207]:
#To return results from function
def hello_func():
    return 'Hello Function.'
print(hello_func())

Hello Function.


In [208]:
def hello_func():
    return 'Hello Function.'
print(hello_func().upper())

HELLO FUNCTION.


In [215]:
def hello_func(greeting, name = 'You'):
    return '{}, {}!'.format(greeting, name)
print(hello_func('Hey','Harshit'))

Hey, Harshit!


In [217]:
def student_info(*args, **kwargs):
    print(args)#results in Tuple
    print(kwargs)#results in Dictionary

student_info('Maths','Art', name = 'John', age = 22)

('Maths', 'Art')
{'name': 'John', 'age': 22}


In [221]:
#Number of days per mornth, First value is placeholder for indexing purpose
month_days = [0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def is_leap(year):
    #Return True for leap year, else False
    return year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)

def days_in_month(year, month):
    if not 1 <= month <= 12:
        return 'Invalid Match'
    if month == 2 and is_leap(year):
        return 29
    return month_days[month]
print(is_leap(2022))
print(days_in_month(2017, 2))

False
28


## Import Modules

In [227]:
print('Imported my_module...')
test = 'Test String'

def find_index(to_search, target): #Finds the index of a value in a sequence
    for i, value in enumerate(to_search):
        if value == target:
            return i
        return -1


Imported my_module...


In [234]:
from my_module import find_index
courses = ['History','Math','Physics','CompSci']
index = find_index(courses, 'Math')
print(index)

ImportError: cannot import name 'find_index' from 'my_module' (C:\Users\HP\my_module.py)

In [256]:
#Standard Library
import random
courses = ['History','Math','Physics','CompSci']

random_course = random.choice(courses)

print(random_course)

History


In [262]:
import math

rads = math.radians(90)
print(math.sin(rads))

1.0


In [264]:
import datetime
import calendar

today = datetime.date.today()
print(today)

print(calendar.isleap(2020))

2021-05-18
True


In [265]:
import os
print(os.getcwd())

C:\Users\HP


In [266]:
import os
print(os.__file__)

C:\Users\HP\anaconda3\lib\os.py


In [267]:
import antigravity

## Intro to Numpy

In [268]:
#To import the Numpy
import numpy as np

In [275]:
a = np.array([1, 3, 5, 7, 9, 11])
print(a)

[ 1  3  5  7  9 11]


In [276]:
#Define (Start, Stop+1, Step) using ARANGE
a = np.arange(1, 12, 2)
print(a)

[ 1  3  5  7  9 11]


In [284]:
#(Start, Stop, #of items) creates array of n equally spaced values
a = np.linspace(5, 15, 5)
print(a)

[ 5.   7.5 10.  12.5 15. ]


In [286]:
#Zero array defined by (Rows, Columns)
a = np.zeros((4,2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [287]:
#One array defined by (Rows, Columns)
a = np.ones((3,3), dtype=np.int16)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [291]:
#Builds array of ((R,C), desired value)
a = np.full((3,), 10)
print(a)

[10 10 10]


In [307]:
#Convert str to integer value and builds array
a = np.fromstring('25 30 35 40', dtype=np.int, sep=' ')
print(a)

[25 30 35 40]


In [308]:
#2-D list inside a list
a = np.array([[1,3,5],[7,9,11]])
print(a)

[[ 1  3  5]
 [ 7  9 11]]


In [ ]:
# _like gives new array in the same shape as the argument a
b = np.zeros_like(a)
print(b)

## Numpy Array Attributes

In [309]:
#To get number of items in array
print (a.size)

6


In [313]:
#To get dimension of array
print(a.shape)
print(a.ndim)

(2, 3)
2


In [312]:
#To get itemsize(bytes of memory for each item)
print(a.itemsize)

4


In [314]:
#To get the data type
print(a.dtype)

int32


In [315]:
#To get the whole array memory
print(a.nbytes) # same as a.size*a.itemsize

24


## Indexing and Slicing

In [316]:
print(a)
print(a[1])
print(a[0][2])
print(b[2:4])

print(a[:1])
print(a[1:3:2])
print(a[:, 1:2])  # all elements on dimension 0, only element 1 on dimension 1

[[ 1  3  5]
 [ 7  9 11]]
[ 7  9 11]
5
[3]
[[1 3 5]]
[[ 7  9 11]]
[[3]
 [9]]
